"""M7 campaign artifacts: YARA rules, Frida hunt scripts, and STIX 2.1 bundles.

Paper 4.7 requires each analysis to emit artifacts a SOC can act on immediately:
"Auto-generated YARA rules and the Frida scripts that exposed the behaviour - so a SOC can
immediately hunt for variants" plus "STIX/TAXII export for SIEMs, firewalls, and channel
filters".

DESIGN INTENT -- HUNT VARIANTS, NOT THE SAMPLE
    A rule that only matches one SHA-256 is worthless: the attacker ships a new build every
    day. These generators therefore key on the *invariants* of a campaign rather than the
    file:
      * package-name token sets. The real cluster found in this corpus
        (us.mobileandroidangryfix.mbankingfixflash, au.androidanti.antimbanking.fixcambankpost,
        com.mbankingangryboomandroid.flashangryinsta, au.mbankingcamangryled.boombank, ...)
        is generated by shuffling a fixed token vocabulary, so the TOKENS are the signature
        even though every package name and hash differs;
      * the permission constellation that enables the capability;
      * runtime-observed drop paths and dynamically loaded DEX names.

    Every generated artifact records the evidence node IDs it derives from, so a reviewer can
    trace a rule back to the observation that justified it -- the same grounding discipline
    the evidence ledger applies to GenAI claims.

    Nothing here emits a malicious artifact: a YARA rule, a passive Frida observer, and a
    STIX indicator are all defensive detection content.
"""
from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Iterable

#: Tokens that recur in machine-generated dropper package names. Used to derive a campaign
#: fingerprint rather than matching a single build.
_TOKEN_SPLIT = re.compile(r"[^a-z0-9]+")
_GENERIC_TOKENS = {
    "com", "org", "net", "app", "apps", "android", "mobile", "us", "eu", "au", "uk", "de",
    "free", "new", "the", "my", "pro", "lite", "test", "demo", "release", "main", "core",
}
_MIN_TOKEN_LENGTH = 3
#: A valid YARA identifier.
_IDENT = re.compile(r"[^A-Za-z0-9_]")


def _yara_escape(value: str) -> str:
    """Escape a string for a YARA double-quoted text string."""
    return value.replace("\\", "\\\\").replace('"', '\\"')


def _identifier(value: str, fallback: str = "drishti_rule") -> str:
    ident = _IDENT.sub("_", value).strip("_")
    if not ident or ident[0].isdigit():
        ident = f"r_{ident}"
    return ident or fallback


#: Vocabulary observed in machine-generated Android dropper package names.
#:
#: Splitting on punctuation alone is not enough. The generator CONCATENATES tokens without
#: separators, so `us.mobileandroidangryfix.mbankingfixflash` yields the useless compound
#: segments "mobileandroidangryfix" and "mbankingfixflash" -- neither of which appears in a
#: sibling build. Matching this vocabulary as substrings recovers the shared units
#: (mbanking, android, angry, fix, flash, ...) that actually persist across the campaign,
#: which is what makes a generated YARA rule hunt variants instead of one hash.
_CAMPAIGN_VOCAB: tuple[str, ...] = (
    "mbanking", "banking", "bank", "post", "anti", "angry", "boom", "insta", "shell",
    "flash", "cam", "led", "fix", "wallet", "paytm", "paytt", "alipay", "upi", "otp",
    "sms", "vpn", "clean", "boost", "secur", "update", "player", "flashlight", "loader",
    "crypt", "miner", "wall", "screen", "recover", "verify", "kyc", "gov", "tax",
)
#: Substring hits shorter than this are too noisy to use as YARA strings.
_MIN_VOCAB_TOKEN = 3


def package_tokens(package: str | None) -> list[str]:
    """Extract campaign-significant tokens from a package name.

    Returns punctuation-delimited segments plus any campaign-vocabulary units found as
    substrings, so concatenated generator output still yields shared tokens.
    """
    if not package:
        return []
    lowered = package.lower()

    # Vocabulary units: the cross-build invariants worth matching.
    vocab_hits = [w for w in _CAMPAIGN_VOCAB
                  if len(w) >= _MIN_VOCAB_TOKEN and w in lowered]
    # Collapse nesting WITHIN the vocabulary only: "mbanking" already implies "banking" and
    # "bank", so keeping all three lets one lexical signal satisfy an "N of" condition three
    # times over and overstates how much independent evidence the rule has.
    #
    # Crucially this collapse must NOT consider the literal package segments. A vocabulary
    # token is almost always a substring of the compound segment it came from
    # ("mbanking" in "mbankingfixflash"), so comparing across the two sets deletes every
    # campaign invariant and leaves only build-specific compounds that no sibling shares --
    # measured effect: sibling recall fell from 4/5 to 0/5.
    vocab: list[str] = []
    for token in sorted(vocab_hits, key=len, reverse=True):
        if any(token != kept and token in kept for kept in vocab):
            continue
        vocab.append(token)

    ordered: list[str] = []

    def add(token: str) -> None:
        if len(token) >= _MIN_TOKEN_LENGTH and token not in _GENERIC_TOKENS \
                and token not in ordered:
            ordered.append(token)

    for token in vocab:
        add(token)
    # Then the literal segments, which pin this particular build.
    for segment in _TOKEN_SPLIT.split(lowered):
        add(segment)
    return ordered


@dataclass
class GeneratedArtifact:
    kind: str
    filename: str
    content: str
    #: Ledger node IDs that justify this artifact.
    evidence_refs: list[str] = field(default_factory=list)
    notes: list[str] = field(default_factory=list)


def _collect(result) -> dict:
    """Pull the fields the generators need out of a pipeline AnalysisResult."""
    verdict = result.verdict
    static = result.static or {}
    dynamic = result.dynamic or {}
    nodes = list(result.ledger or [])
    observed = [n for n in nodes if n.get("type") == "dynamic_obs"]
    package = (dynamic.get("package")
               or static.get("package")
               or static.get("package_name"))
    permissions = [p for p in (static.get("permissions") or []) if isinstance(p, str)]
    combos = [c.get("label") for c in (static.get("combos") or []) if c.get("label")]
    iocs = static.get("iocs") or []
    urls = []
    for entry in iocs:
        value = entry.get("value") if isinstance(entry, dict) else str(entry)
        if value:
            urls.append(value)
    return {
        "sha256": verdict.sha256,
        "package": package,
        "permissions": permissions,
        "combos": combos,
        "urls": urls,
        "techniques": list(verdict.attack_techniques or []),
        "observed_nodes": observed,
        "observed_mitre": list(dynamic.get("mitre_observed") or []),
        "dynamic_status": verdict.dynamic_status,
        "severity": verdict.severity_band,
        "score": verdict.threat_score,
        "summary": verdict.summary,
        "evidence_refs": list(verdict.evidence_refs or []),
        "nodes": nodes,
    }


def _observed_paths(observed_nodes: Iterable[dict]) -> list[str]:
    """Runtime drop paths / dynamically loaded DEX names, from observation content."""
    paths: list[str] = []
    for node in observed_nodes:
        content = node.get("content") or ""
        for match in re.finditer(r"path=([^\s]+)", content):
            candidate = match.group(1)
            name = candidate.rsplit("/", 1)[-1]
            # A per-install randomised name is not a useful literal; its EXTENSION and
            # parent directory are. Keep the basename only when it looks stable.
            if name and not re.fullmatch(r"[a-z0-9]{12,}\.(dex|jar|apk)", name):
                paths.append(name)
    return sorted(set(paths))


def generate_yara_rule(result, *, rule_name: str | None = None) -> GeneratedArtifact:
    """Emit a YARA rule that hunts the campaign, not just this build."""
    data = _collect(result)
    package = data["package"] or ""
    tokens = package_tokens(package)
    name = _identifier(rule_name or f"DRISHTI_{(package or data['sha256'][:12])}")
    refs = data["evidence_refs"] + [n["id"] for n in data["observed_nodes"]]
    notes: list[str] = []

    strings: list[tuple[str, str]] = []
    for index, token in enumerate(tokens[:8]):
        strings.append((f"$tok{index}", token))
    for index, perm in enumerate(sorted({p.split(".")[-1] for p in data["permissions"]
                                        if p})[:10]):
        strings.append((f"$perm{index}", f"android.permission.{perm}"))
    for index, path in enumerate(_observed_paths(data["observed_nodes"])[:5]):
        strings.append((f"$drop{index}", path))
    hosts: list[str] = []
    for url in data["urls"]:
        match = re.match(r"https?://([^/]+)", url)
        if match and not match.group(1).endswith((
                "google.com", "googleapis.com", "googlesyndication.com", "adobe.com",
                "android.com", "gstatic.com")):
            hosts.append(match.group(1))
    for index, host in enumerate(sorted(set(hosts))[:6]):
        strings.append((f"$host{index}", host))

    token_ids = [sid for sid, _ in strings if sid.startswith("$tok")]
    perm_ids = [sid for sid, _ in strings if sid.startswith("$perm")]
    drop_ids = [sid for sid, _ in strings if sid.startswith("$drop")]
    host_ids = [sid for sid, _ in strings if sid.startswith("$host")]

    # Build the condition so that a campaign-name hint alone is never sufficient: names are
    # cheap for an attacker to change, whereas the permission constellation reflects the
    # capability the malware actually needs. Requiring BOTH keeps recall across siblings
    # while refusing to fire on an unrelated app that merely shares a word like "bank".
    name_clause = ""
    if len(token_ids) >= 2:
        name_clause = f"2 of ({', '.join(token_ids)})"
    elif token_ids:
        name_clause = f"any of ({', '.join(token_ids)})"
    capability_clause = ""
    if len(perm_ids) >= 3:
        capability_clause = f"3 of ({', '.join(perm_ids)})"
    elif perm_ids:
        capability_clause = f"any of ({', '.join(perm_ids)})"

    strong_clauses: list[str] = []
    # Runtime drops and non-benign hosts are specific enough to stand alone.
    if drop_ids:
        strong_clauses.append(f"any of ({', '.join(drop_ids)})")
    if host_ids:
        strong_clauses.append(f"any of ({', '.join(host_ids)})")

    branches: list[str] = []
    if name_clause and capability_clause:
        branches.append(f"({name_clause} and {capability_clause})")
    elif name_clause or capability_clause:
        # Only one axis of evidence: keep the rule but say so, since precision will be lower.
        branches.append(f"({name_clause or capability_clause})")
        notes.append("Only one evidence axis was available (name tokens or permissions, not "
                     "both), so this rule is broader than usual. Review before deploying to "
                     "a blocking control.")
    branches.extend(strong_clauses)
    if not branches:
        branches.append("false")
        notes.append("Insufficient invariant evidence for a variant-hunting rule; the rule "
                     "is emitted disabled rather than as a hash-only match.")

    # Require the ZIP local-file-header magic so the rule cannot fire on arbitrary files.
    condition = "uint32(0) == 0x04034b50 and (" + " or ".join(branches) + ")"
    if not strings:
        strings = [("$zip", "PK")]

    body = [f"rule {name}", "{", "    meta:"]
    body.append(f'        author = "DRISHTI automated triage"')
    body.append(f'        description = "Campaign-level hunt rule derived from analysed sample"')
    body.append(f'        drishti_sha256 = "{data["sha256"]}"')
    if package:
        body.append(f'        observed_package = "{_yara_escape(package)}"')
    body.append(f'        severity = "{data["severity"]}"')
    body.append(f'        threat_score = "{data["score"]}"')
    if data["techniques"]:
        body.append(f'        mitre_mobile = "{", ".join(data["techniques"])}"')
    body.append(f'        dynamic_provenance = "{data["dynamic_status"]}"')
    if refs:
        body.append(f'        evidence_refs = "{", ".join(refs[:12])}"')
    body.append(f'        generated_at = "{datetime.now(timezone.utc).isoformat()}"')
    body.append("    strings:")
    for sid, value in strings:
        body.append(f'        {sid} = "{_yara_escape(value)}" nocase')
    body.append("    condition:")
    body.append(f"        {condition}")
    body.append("}")

    notes.append("Keys on package-name tokens, the permission constellation and observed "
                 "runtime drops so sibling builds with new hashes still match.")
    return GeneratedArtifact("yara", f"{name}.yar", "\n".join(body) + "\n", refs, notes)


#: MITRE technique -> the Java surface a hunter should watch. Passive observation only.
_TECHNIQUE_HOOKS: dict[str, list[tuple[str, str]]] = {
    "T1582": [("android.telephony.SmsManager", "sendTextMessage"),
              ("android.telephony.SmsMessage", "getMessageBody")],
    "T1417": [("android.view.WindowManager", "addView")],
    "T1516": [("android.accessibilityservice.AccessibilityService", "onAccessibilityEvent")],
    "T1407": [("dalvik.system.DexClassLoader", "$init"),
              ("dalvik.system.BaseDexClassLoader", "$init")],
    "T1521": [("javax.crypto.Cipher", "doFinal")],
    "T1426": [("android.telephony.TelephonyManager", "getSimOperatorName"),
              ("android.os.Build", "getRadioVersion")],
    "T1409": [("android.content.ContentResolver", "query")],
    "T1414": [("android.content.ClipboardManager", "getPrimaryClip")],
    "T1641.001": [("android.content.ClipboardManager", "setPrimaryClip")],
    "T1437": [("java.net.URL", "openConnection")],
}


def generate_frida_script(result) -> GeneratedArtifact:
    """Emit the passive Frida observer for the techniques this sample exhibited."""
    data = _collect(result)
    techniques = [t for t in dict.fromkeys(data["techniques"] + data["observed_mitre"])]
    selected = [(t, hooks) for t in techniques for hooks in [_TECHNIQUE_HOOKS.get(t)] if hooks]
    refs = data["evidence_refs"] + [n["id"] for n in data["observed_nodes"]]

    lines = [
        "/* DRISHTI variant-hunting hooks.",
        f" * Derived from sample {data['sha256']}",
        f" * package: {data['package'] or 'unknown'}",
        f" * techniques: {', '.join(techniques) or 'none'}",
        f" * dynamic provenance: {data['dynamic_status']}",
        f" * evidence: {', '.join(refs[:12]) or 'n/a'}",
        " *",
        " * PASSIVE OBSERVER ONLY. Each hook logs and then calls the original implementation;",
        " * nothing is blocked, injected or modified, and no argument value is exfiltrated.",
        " * Sensitive arguments are replaced with a redaction marker before logging, matching",
        " * the redaction contract used by the M3 harness.",
        " * Run inside an isolated analysis sandbox, never on a production device.",
        " */",
        "'use strict';",
        "",
        "function report(technique, surface, detail) {",
        "    send({ drishti: true, technique: technique, surface: surface, detail: detail });",
        "}",
        "",
        "function redact(value) {",
        "    if (value === null || value === undefined) return '';",
        "    var text = String(value);",
        "    if (text.length > 160) text = text.substring(0, 160) + '...';",
        "    return text.replace(/\\b\\d{4,}\\b/g, '[REDACTED:DIGITS]');",
        "}",
        "",
        "Java.perform(function () {",
    ]
    if not selected:
        lines.append("    report('none', 'none', 'no technique-specific hooks were derived');")
    for technique, hooks in selected:
        for class_name, method in hooks:
            lines += [
                "    try {",
                f"        var k = Java.use('{class_name}');",
                f"        if (k['{method}']) {{",
                f"            var overloads = k['{method}'].overloads;",
                "            overloads.forEach(function (impl) {",
                "                impl.implementation = function () {",
                "                    var args = [];",
                "                    for (var i = 0; i < arguments.length; i++) "
                "args.push(redact(arguments[i]));",
                f"                    report('{technique}', "
                f"'{class_name}.{method}', args.join(' | '));",
                "                    return impl.apply(this, arguments);",
                "                };",
                "            });",
                "        }",
                "    } catch (e) {",
                f"        send({{ drishti: true, hook_error: '{class_name}.{method}', "
                "error: String(e) }});",
                "    }",
            ]
    lines += ["});", ""]
    notes = ["Hooks are limited to the techniques this sample actually exhibited, so the "
             "script stays small enough to run against a live variant without destabilising it."]
    package_slug = _identifier(data["package"] or data["sha256"][:12])
    return GeneratedArtifact("frida", f"hunt_{package_slug}.js", "\n".join(lines), refs, notes)


def _stix_id(kind: str, seed: str) -> str:
    """Deterministic STIX id so re-analysing a sample yields a stable bundle."""
    import hashlib
    import uuid
    digest = hashlib.sha256(f"drishti:{kind}:{seed}".encode()).digest()[:16]
    return f"{kind}--{uuid.UUID(bytes=digest, version=5)}"


def generate_stix_bundle(result) -> GeneratedArtifact:
    """Emit a STIX 2.1 bundle for SIEM / TAXII ingestion."""
    data = _collect(result)
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%S.%fZ")
    sha = data["sha256"]
    identity_id = _stix_id("identity", "drishti")
    objects: list[dict] = [{
        "type": "identity", "spec_version": "2.1", "id": identity_id,
        "created": now, "modified": now,
        "name": "DRISHTI automated triage", "identity_class": "system",
    }]

    file_id = _stix_id("file", sha)
    file_object = {
        "type": "file", "spec_version": "2.1", "id": file_id,
        "hashes": {"SHA-256": sha},
    }
    if data["package"]:
        file_object["name"] = f"{data['package']}.apk"
    objects.append(file_object)

    malicious = data["severity"] in ("High", "Critical")
    indicator_id = _stix_id("indicator", sha)
    objects.append({
        "type": "indicator", "spec_version": "2.1", "id": indicator_id,
        "created_by_ref": identity_id, "created": now, "modified": now,
        "name": f"DRISHTI {data['severity']} verdict for {data['package'] or sha[:12]}",
        "description": (data["summary"] or "")[:900],
        "indicator_types": ["malicious-activity"] if malicious else ["anomalous-activity"],
        "pattern": f"[file:hashes.'SHA-256' = '{sha}']",
        "pattern_type": "stix", "pattern_version": "2.1",
        "valid_from": now,
        "confidence": int(round(float(result.verdict.confidence) * 100)),
        "labels": [f"drishti-score-{data['score']}",
                   f"drishti-severity-{data['severity'].lower()}",
                   f"dynamic-{data['dynamic_status']}"],
    })

    malware_id = _stix_id("malware", data["package"] or sha)
    objects.append({
        "type": "malware", "spec_version": "2.1", "id": malware_id,
        "created_by_ref": identity_id, "created": now, "modified": now,
        "name": data["package"] or f"unknown-{sha[:12]}",
        "is_family": False,
        "malware_types": ["trojan"] if malicious else ["unknown"],
        "implementation_languages": ["java"],
        "architecture_execution_envs": ["android"],
        "description": (data["summary"] or "")[:900],
    })
    objects.append({
        "type": "relationship", "spec_version": "2.1",
        "id": _stix_id("relationship", f"ind-mal-{sha}"),
        "created_by_ref": identity_id, "created": now, "modified": now,
        "relationship_type": "indicates",
        "source_ref": indicator_id, "target_ref": malware_id,
    })

    # MITRE Mobile techniques as attack-patterns, related to the malware object.
    for technique in data["techniques"]:
        pattern_id = _stix_id("attack-pattern", technique)
        objects.append({
            "type": "attack-pattern", "spec_version": "2.1", "id": pattern_id,
            "created_by_ref": identity_id, "created": now, "modified": now,
            "name": technique,
            "external_references": [{
                "source_name": "mitre-attack",
                "external_id": technique,
                "url": f"https://attack.mitre.org/techniques/{technique.replace('.', '/')}/",
            }],
        })
        objects.append({
            "type": "relationship", "spec_version": "2.1",
            "id": _stix_id("relationship", f"{sha}-{technique}"),
            "created_by_ref": identity_id, "created": now, "modified": now,
            "relationship_type": "uses",
            "source_ref": malware_id, "target_ref": pattern_id,
        })

    # Network IOCs, excluding well-known benign infrastructure.
    for url in data["urls"][:25]:
        match = re.match(r"https?://([^/]+)", url or "")
        if not match:
            continue
        host = match.group(1)
        if host.endswith(("google.com", "googleapis.com", "googlesyndication.com",
                          "adobe.com", "android.com", "gstatic.com")):
            continue
        objects.append({
            "type": "indicator", "spec_version": "2.1",
            "id": _stix_id("indicator", f"{sha}-{host}"),
            "created_by_ref": identity_id, "created": now, "modified": now,
            "name": f"Network indicator {host}",
            "indicator_types": ["anomalous-activity"],
            "pattern": f"[domain-name:value = '{host}']",
            "pattern_type": "stix", "pattern_version": "2.1", "valid_from": now,
        })

    # Only independently observed runtime behaviour becomes observed-data.
    if data["dynamic_status"] == "observed":
        for node in data["observed_nodes"]:
            objects.append({
                "type": "observed-data", "spec_version": "2.1",
                "id": _stix_id("observed-data", f"{sha}-{node['id']}"),
                "created_by_ref": identity_id, "created": now, "modified": now,
                "first_observed": now, "last_observed": now,
                "number_observed": 1,
                "object_refs": [file_id],
                "x_drishti_evidence_ref": node["id"],
                "x_drishti_observation": (node.get("content") or "")[:400],
                "x_drishti_provenance": "observed-in-isolated-detonator",
            })

    bundle = {"type": "bundle", "id": _stix_id("bundle", sha), "objects": objects}
    refs = data["evidence_refs"] + [n["id"] for n in data["observed_nodes"]]
    return GeneratedArtifact(
        "stix", f"stix_{sha[:16]}.json", json.dumps(bundle, indent=2), refs,
        ["STIX 2.1 bundle for TAXII publication. Simulated behaviour is never emitted as "
         "observed-data; only SHA-matched detonator output is."])


def generate_all(result) -> list[GeneratedArtifact]:
    """Produce every campaign artifact for one analysis."""
    return [generate_yara_rule(result),
            generate_frida_script(result),
            generate_stix_bundle(result)]
